var nome = prompt("Ciao prode avventuriero, Benvenuto all'Hotel Medieval, con chi ho il piacere di parlare? Potresti dirmi il tuo Nome?");
console.log(nome);
var cognome = prompt('Che maestoso nome.. fai sicuramente parte di una importante casata vero? Qual è il tuo cognome, straniero?');
console.log(cognome);
var colore = prompt('Ohoh.! Proprio come immaginavo! Sai, dal colore preferito di una persona, si riesce a capire molto del suo carattere. Qual è il tuo?');
console.log(colore);
var password = name + cognome + colore + '19';
document.write("<p>Perfetto, ora che sei entrato nello spirito medievale, possiamo fornirti la tua password personale per accedere al nostro Wi-FI, che nel tuo caso è: </p>");
document.writeln(password);
document.writeln("<p>Con i miei più sinceri ossequi, buona permanenza nel nostro Hotem Medieval!</>");
